### ISSUE TITLE
Could you please share the homemade scripts in Paired-HiC?

### ISSUE THREAD

**Issue by Xuyuch** [Xieeeee/Droplet-Hi-C#3]
Dear Yang,
May I ask for the homemade perl, python, and R code used in your alignment? They are mentioned in the code here and saved in '/projects/ps-renlab/y2xie/scripts/Paired-HiC/':
```
perl ${script_dir}/phc.pairsam_add_bc.v2.pl ${map_dir}/${s}_${genome}.sorted.pairsam
/home/y2xie/anaconda3/envs/seurat/bin/Rscript ${script_dir}/phc.summarize_pairs_lec.R ${map_dir}/${s}_${genome}.sc.pairdedup.txt
/home/y2xie/anaconda3/envs/seurat/bin/Rscript ${script_dir}/phc.plot_fragment.R ${map_dir}/${s}_${genome}.sc.pairs
python ${script_dir}/phc.count_pairs_sc.py --input ${map_dir}/${s}_${genome}.sc.pairs.gz --output ${map_dir}/${s}_${genome}.PairCount
```
Great thanks.

Best
Yuchen

**Comment by Xieeeee** [comment]
Hi Yuchen,
Apologize that I forget to upload them. Please find them at https://github.com/Xieeeee/Droplet-Hi-C/tree/main/01.pre-process/scripts.

Best,
Yang

**Comment by Xuyuch** [comment]
I can see them now. Thank you!
Best,
Yuchen
