### ISSUE TITLE
May I ask for the code for mapping RNA and DNA barcodes?

### ISSUE THREAD

**Issue by Xuyuch** [Xieeeee/Droplet-Hi-C#5]
Hi Yang,
   Thanks for all your previous help. I am really closed to get the final step to the processed data. However, I have difficulties in mapping the barcodes generated in HiC paired to RNA barcode. In your manuscript, I saw you manually paired the 2 barcodes(Enclosed screencut beneath). May I know more details about how it works and Do you have any established codes you could share? Thanks a lot!
  
Yuchen  
![image](https://github.com/user-attachments/assets/7cf74e18-f18f-48f6-a498-367bd4bcc656)

**Comment by Xieeeee** [comment]
Hi Xuyuch,
Sure! You can find this [file](https://github.com/Xieeeee/Droplet-Paired-Tag/blob/main/01.pre-process/supp/arc_bc-translation.txt) which is generated using the barcodes whitelist information provided by 10XGenomics.

Best,
Y

**Comment by Xuyuch** [comment]
Great! Thanks a lot!
Best
Yuchen
