### ISSUE TITLE
Files of 'cluster' in phc.sc_splitPairs_v2.py

### ISSUE THREAD

**Issue by flysheeeep** [Xieeeee/Droplet-Hi-C#6]
Hi, xie,
Fantastic work on scHiC. I want to utilize the '.pair.gz' file that u upload to GEO in my research, and appreciate that ur uploading the preprocess script which do me a great favor.
The python script 'phc.sc_splitPairs_v2.py' intending to split each '.pair.gz' to multiple '.pair.gz' with different cell cluster. And I have several questions
1. And the args '--cluster' need the column 'cluster', did the cluster information of each cell generated with Higash? Could u please provide me the cluster files? Or have u tried spliting pairs to each cell just with the barcode, it may create thonsands of pair file?

Thanks again for your fantastic work and hope for your reply!
All the best

**Comment by Xieeeee** [comment]
Hi there,
Thanks for your interest in Droplet Hi-C! For your question, we are splitting the libraries into thousands of single cells. The reason I am doing this is that schicluster I used to perform imputation and downstream analysis did computation on per cell basis. I know this is annoying to blow the disk with a lot of pair files, but considering the current analysis tools for scHi-C this seems to be the easiest way to do.

Let me know if you have more questions.

Best.
Yang

**Comment by flysheeeep** [comment]
Got it! Thx for your reply. 
And I notice that u count valid pair per barcode, did u filter cells with little valid pairs before downstream analysis? and if so, any advice on the cutoff number?
With ur advice, i will try to split '.pair' file with barcode base on your script.

Thx again for ur reply!
All the best!

**Comment by Xieeeee** [comment]
What we commonly do is to plot a pairs number by rank scatterplot similar to the one you would see in 10X scRNA-seq report, and then we define the "elbow" point as the cutoff used for filtering, but sometimes we also choose arbitrary cutoff like 30k or so if the automatic defined cutoff doesn't make sense. The exact number would depends on the sequencing depth for each library.

Best,
Y

**Comment by flysheeeep** [comment]
Got it! Thanks a lot 👍

All the best!
