### ISSUE TITLE
Question about paired Hi-C barcode

### ISSUE THREAD

**Issue by flysheeeep** [Xieeeee/Droplet-Hi-C#7]
Hi, xie,
sorry to bother again😂
I just found u uploaded matching relationship of barcode in supp, and I am wondering if it can apply to all the paired Hi-C files in https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE253407. And the ‘*_valid_bc.txt.gz’ in some dataset, am wondering what is the criteria of selecting valid cell.

Thanks again for your fantastic work and hope for your reply!
All the best

Xue

**Comment by Xieeeee** [comment]
Hi Xue,
Not at all. The pairing relationship can be applied to all Paired Hi-C files in the GEO. Besides, for barcode selection you might find some details [here](https://github.com/Xieeeee/Droplet-Hi-C/issues/6#issuecomment-2516344849)

Best,
Yang

**Comment by Xieeeee** [comment]
I think I refer to an answer to your previous question. Just wanna elaborate more to prevent confusion. The valid bc would looks like this once we plot the total pairs vs ranks: 
![LC465_25k_cells select](https://github.com/user-attachments/assets/ed1556d7-f4f5-484b-8833-c14c2307c074)

The criteria is finding the elbow point of switching in this plot. We used a method that is implemented in the early version of cellranger. Although not exactly the same, you can find some related information [here](https://www.10xgenomics.com/cn/support/software/cell-ranger/latest/advanced/cr-barcode-rank-plot)

**Comment by flysheeeep** [comment]
I got it. Your scripts and descriptions really do me a great favor!
Thx again!

All the best!

Xue
